#!/bin/bash

echo "🎯 Presentation Generator Demo"
echo "================================"
echo ""
echo "✅ Application Status:"
echo "   - Frontend: http://localhost:3000"
echo "   - Backend: http://localhost:3001"
echo ""
echo "🎨 Features Available:"
echo "   • AI-powered content generation (with valid OpenAI API key)"
echo "   • Professional template fallback"
echo "   • Account management focused presentations"
echo "   • 5-slide PowerPoint generation"
echo "   • Clean, modern web interface"
echo ""
echo "📝 How to Use:"
echo "   1. Open http://localhost:3000 in your browser"
echo "   2. Enter a presentation topic (try the example prompts)"
echo "   3. Click 'Generate Presentation'"
echo "   4. Download your PowerPoint file"
echo ""
echo "🔑 For AI-powered content:"
echo "   1. Get an API key from https://platform.openai.com/api-keys"
echo "   2. Edit .env file: OPENAI_API_KEY=sk-your-key-here"
echo "   3. Restart the application"
echo ""
echo "🚀 The application is ready to use!"
